[technote]
id = "DMTN-278"
series_id = "DMTN"
canonical_url = "https://dmtn-278.lsst.io"
github_url = "https://github.com/lsst-dm/dmtn-278"
github_default_branch = "main"
date_created = 2023-12-30T00:28:21Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"

[[technote.authors]]
name.given = "Frossie"
name.family = "Economou"
orcid = "https://orcid.org/0000-0002-8333-7615"
internal_id = "economouf"
[[technote.authors.affiliations]]
name = "Rubin Observatory Project Office"
internal_id = "RubinObs"
address = "950 N. Cherry Ave., Tucson, AZ  85719, USA"
